import './globals.css'
import Navbar from './components/navigation/navbar'

import Signup from './login_signup/login.js';
import Footer from './components/footer'
import localFont  from '@next/font/local'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const generalSansBold = localFont({
//   src: './fonts/GeneralSans-Bold.ttf',
//   variable: '--font-generalSans-bold',
// })

// const generalSansRegular = localFont({
//   src: './fonts/GeneralSans-Regular.ttf',
//   variable: '--font-generalSans-regular',
// })

// const generalSansLight = localFont({
//   src: './fonts/GeneralSans-Light.ttf',
//   variable: '--font-generalSans-light',
// })

export default function RootLayout({ children }) {
  return (
    // <html lang="en" className={`${generalSansBold.variable} ${generalSansRegular.variable} ${generalSansLight.variable}`}>
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
=======
      <body>
        <Navbar />
>>>>>>> main
        {children}
        < Footer />
      </body>  
    </html>
  )
}