import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navigation/navbar'
import Login from './login_signup/login.js';
import Signup from "./login_signup/signup.js";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   {/* <body className={inter.className}>
    //     {children}
    //     </body> */}
    // </html>
    <Signup  check="Brand" />
  );
}
{/* <Signup check="Brand" /> */}
