import './globals.css'
import Navbar from './components/navigation/navbar'

import Signup from './login_signup/login.js';
import Footer from './components/footer'
import localFont  from '@next/font/local'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang="en" className={`${generalSansBold.variable} ${generalSansRegular.variable} ${generalSansLight.variable}`}>
    <html lang="en">
      <body>
        <Navbar />
        {children}
        < Footer />
      </body>  
    </html>
  )
}